const dashboardActions = {
    SET_PROJECTS: "SET_PROJECTS",
    SET_PROJECTS_MODIFIED: "SET_INVITES_MODIFIED",
    SET_INVITES: "SET_INVITES",
    SET_INVITES_MODIFIED: "SET_INVITES_MODIFIED",
    RESET_INVITES_STATE: "RESET_INVITES",
    REMOVE_INVITE: "REMOVE_INVITE",
    SET_INVITE_BOARD_LOCKED: "SET_INVITE_BOARD_LOCKED",
    SET_INVITE_BOARD_UNLOCKED: "SET_INVITE_BOARD_UNLOCKED",
};

export { dashboardActions };
