const sharedActions = {
    MODAL_STACK: "MODAL_STACK",
    PUSH_MODAL_STATE: "PUSH_MODAL_STATE",
    POP_MODAL_STATE: "POP_MODAL_STATE",
    EMPTY_MODAL_STACK: "EMPTY_MODAL_STACK",
    SET_AUTH_LEVEL: "SET_AUTH_LEVEL",
};

export { sharedActions };
