const sharedActions = {
    MODAL_STACK: "MODAL_STACK",
    TOGGLE_NAV: "TOGGLE_NAVBAR",
    PUSH_MODAL_STATE: "PUSH_MODAL_STATE",
    POP_MODAL_STATE: "POP_MODAL_STATE",
    EMPTY_MODAL_STACK: "EMPTY_MODAL_STACK",
    SET_AUTH_LEVEL: "SET_AUTH_LEVEL",
    SET_LOGGED_IN: "SET_LOGGED_IN",
    SET_USER_DATA: "SET_USER_DATA",
};

export { sharedActions };
