const ticketboardActions = {
    SET_DISP_TICKET_INFO: "SET_SET_DISP_TICKET_INFO",
    SET_DISPLAY_SEARCH_FILTER: "SET_DISPLAY_SEARCH_FILTER",
    SET_FILTER_TS_OPEN: "SET_FILTER_TS_OPEN",
    SET_FILTER_TS_IN_PROGRESS: "SET_FILTER_TS_IN_PROGRESS",
    SET_FILTER_TS_PENDING_APPROVAL: "SET_FILTER_TS_PENDING_APPROVAL",
    SET_FILTER_TS_CLOSED: "SET_FILTER_TS_CLOSED",
};

export { ticketboardActions };
