const ticketboardActions = {
    SET_REFRESH_NEEDED: "SET_REFRESH_NEEDED",
    SET_PID: "SET_PID",
    SET_USERS: "SET_USERS",
    SET_TICKETS: "SET_TICKETS",
    SET_DISP_TICKET_INFO: "SET_SET_DISP_TICKET_INFO",
    SET_DISPLAY_SEARCH_FILTER: "SET_DISPLAY_SEARCH_FILTER",
    SET_FILTER_TS_OPEN: "SET_FILTER_TS_OPEN",
    SET_FILTER_TS_IN_PROGRESS: "SET_FILTER_TS_IN_PROGRESS",
    SET_FILTER_TS_PENDING_APPROVAL: "SET_FILTER_TS_PENDING_APPROVAL",
    SET_FILTER_TS_CLOSED: "SET_FILTER_TS_CLOSED",
    SET_CREATE_FORM_INFO: "SET_CREATE_FORM_INFO",
    FLUSH_CREATE_FORM_INFO: "FLUSH_CREATE_FORM_INFO",
    FLUSH_TICKETBOARD_STATE: "FLUSH_TICKETBOARD_STATE",
};

export { ticketboardActions };
