const dashboardFields = {
    PROJECTS: "PROJECTS",
    PROJECTS_MODIFIED: "PROJECTS_MODIFIED",
    INVITES_MODIFIED: "INVITES_MODIFIED",
    INVITES: "INVITES",
    RES_STATUS: "RES_STATUS",
    INVITE_BOARD_LOCKED: "INVITE_BOARD_LOCKED",
};

export { dashboardFields };
