const ticketboardFields = {
    DISPLAY_SEARCH_FILTER: "DISPLAY_SEARCH_FILTER",
    FILTER_TS_OPEN: "FILTER_TS_OPEN",
    FILTER_TS_IN_PROGRESS: "FILTER_TS_IN_PROGRESS",
    FILTER_TS_PENDING_APPROVAL: "FILTER_TS_PENDING_APPROVAL",
    FILTER_TS_CLOSED: "FILTER_TS_CLOSED",
    DISP_TICKET_INFO: "DISP_TICKET_INFO",
};

export { ticketboardFields };
