const ticketboardFields = {
    USERS: "USERS",
    REFRESH_NEEDED: "REFRESH_NEEDED",
    PID: "PID",
    TICKETS: "TICKETS",
    DISPLAY_SEARCH_FILTER: "DISPLAY_SEARCH_FILTER",
    FILTER_TS_OPEN: "FILTER_TS_OPEN",
    FILTER_TS_IN_PROGRESS: "FILTER_TS_IN_PROGRESS",
    FILTER_TS_PENDING_APPROVAL: "FILTER_TS_PENDING_APPROVAL",
    FILTER_TS_CLOSED: "FILTER_TS_CLOSED",
    DISP_TICKET_INFO: "DISP_TICKET_INFO",
    TICKET_MODIFIED: "TICKET_MODIFIED",
    NEW_TICKET_FORM_INFO: "NEW_TICKET_FORM_INFO",
};

export { ticketboardFields };
