const actions = {
    MODAL_ACTIVE: "MODAL_ACTIVE",
    DISPLAY_SEARCH_FILTER: "DISPLAY_SEARCH_FILTER",
    FILTER_TS_OPEN: "FILTER_TS_OPEN",
    FILTER_TS_IN_PROGRESS: "FILTER_TS_IN_PROGRESS",
    FILTER_TS_PENDING_APPROVAL: "FILTER_TS_PENDING_APPROVAL",
    FILTER_TS_CLOSED: "FILTER_TS_CLOSED",
    CREATE_PROJECT_MODAL_OPEN: "CREATE_PROJECT_MODAL_OPEN",
};

export default actions;
